collectors: []
testers:
  - [2, [.7, .3, 0, 0, 0, 0, deep, c95s, e10]
phone_class: Phone
monkey_client_mode: True
data_file_dir:
logs_dir: INVALID
reset_logs: False
weights_file:
  learner:
  e10:
collectors_apks_path:
testers_apks_path:
collectors_clone_script:
testers_clone_script:
prediction_shape: [56, 56]
reward_predictor: [UNetRewardPredictor, unet]
variance_reg_coeff: 0
l1_reg_coeff: 0
iic_coeff: 0
iic_distorter_probabilities: [0, 1]
distort_shift_max_value: 5
prediction_normalizer: linear_normalizer
use_logger: False
action_prob_coeffs: [1., 0.3, 0.1]

coordinator_configs:
  train: False
  evaluate_dir:
  pre_training: False
  collect_before_pre_training: False
  sync_weight: False
  process_configs:
    type: spawn
    queue_size: 5

collector_configs:
  max_episodes:
  max_file_size:
  meta_save_frequency: 
  version_start:

tester_configs:
  max_episodes: 15000000000
  version_window: 10
  max_file_size: 10
  past_rewards_window: 20
  past_rewards_threshold: .75
  learn: False
  loss_threshold: 0.05
  file_dir: INVALID
  weight_reset_frequency:
  learning_rate: 0.001
  learner_configs:
    batch_size: 32
    correct_distributions: True
    augmenting_correction: True
    strict_correction: False
    epochs_per_version: 10

learner_configs:
  batch_size: 32
  shuffle: True
  correct_distributions: True
  augmenting_correction: False
  strict_correction: True
  epochs_per_version: 20
  data_portion_per_epoch: 1
  save_dir:
  validation_dir:

environment_configs:
  action_type_count: 3
  recreate_on_app: True
  restart_after_install: True
  steps_per_app: 300
  steps_per_app_reopen: 100
  steps_per_in_app_check: 1
  in_app_check_trials: 3
  force_app_on_top: True
  black_screen_trials: 2
  global_equality_threshold: 512
  pixel_equality_threshold: 1
  animation_monitor_time: 0
  action_max_wait_time: 1
  action_offset_wait_time: .5
  action_freeze_wait_time: 0
  screenshots_interval: 0.1
  remove_bad_apps: False
  shuffle_apps: False
  calculate_reward: False
  start_phone_fresh: True
  app_start_callback:
  app_end_callback: kill -9 `cat .{device}.pid` || true
  fatal_error_callback: kill -10 `cat .{device}.pid` || true
  fatal_error_handled_callback: kill -12 `cat .{device}.pid` || true

browser_configs:
  window_size: [640, 480]
  apps_count: 10
  mozilla_path: /usr/bin/firefox
  user_agent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16
  query_max_length: 10
  screenshots_dir: .
  scroll_min_value: 200
  scroll_max_value: 600
  headless: True

phone_configs:
  screen_shape: [234, 224]
  dummy_mode_configs:
    - 4
    - 2
    - 15
    - 5
    - 10
    - 2
    - 0
    - 1
    - 0
    - .5
  snapshot_load_wait_time: -5
  install_wait_time: 10
  app_start_max_wait_time: 15
  after_app_start_wait_time: 10
  app_exit_wait_time: 5 #30
  phone_start_boot_max_wait_time: 300
  phone_restart_kill_max_wait_time: 300
  phone_boot_wait_time: 10
  unlock: True
  disable_input_methods: True
  maintain_visited_activities: False
  install_apks: False
  avd_path:
  aapt_path:
  adb_path: /home/$USER/android-sdk/platform-tools/adb
  emulator_path:
  emma_jar_path:
  screenshots_dir: .
  grep_command: grep
  timeout_template: 'timeout -t {}'
  apk_install_command: 'install -r'
  app_stop_command: 'kill `pgrep -f {}`'
  current_activity_grep: mResumedActivity
  current_activity_regex: '.*HistoryRecord{.+ (.+)}.*'
  is_in_app_grep: "-m 1 '* TaskRecord'"
  is_in_app_regex: '.*TaskRecord{.+ #\d+ .+ (.+)}'
  scroll_min_value: 100
  scroll_max_value: 300
  scroll_event_count: 5
  keyboard_text_max_length: 15


screen_preprocessor_configs:
  crop_top_left: [10, 0]
  crop_size: [224, 224]
  resize_size: [224, 224]
  grayscale: False
  scale_color: False
  equalize_background: False
  contrast_alpha: -1

simple_reward_predictor_configs:
  screen_encoder_configs:
    padding_type: SAME
    kernel_sizes: [4, 2, 4, 4]
    filter_nums: [8, 16, 32, 64]
    stride_sizes: [1, 1, 1, 1]
    maxpool_sizes: [1, 5, 2, 1]

unet_reward_predictor_configs:
  screen_encoder_configs:
    inner_configs:
      alpha: 0.5
      weights: imagenet
    output_layer_names:
      - block_16_project
      - block_13_expand_relu
      - block_6_expand_relu

  reward_decoder_configs:
    filter_nums: [256, 128]
    kernel_sizes: 3
    stride_sizes: 2
    padding_types: SAME

random_reward_predictor_configs: {}
  
collector_logger_configs:
  scalar_log_frequency: 1
  image_log_frequency: 1
  coverage_log_frequency: 15
  prediction_overlay_factor: 0.4
  cluster_color_size: 2
  steps_per_new_file: 300
  log_preprocessed_screen: False
  log_reward_prediction: True
  chunk_start: 0

clusterer_configs:
  default:
    start_clickable_threshold: 0.90
    clickable_threshold_speed: 0
    clickable_threshold_speed_step: 1
    speed_steps_per_clickable_threshold_reset: 1
    distance_threshold: 2.99
    cluster_count_threshold: 4
  c90s:
    distance_threshold: 1.99
    cluster_count_threshold: 6
  c97s:
    distance_threshold: 1.99
    cluster_count_threshold: 6
    start_clickable_threshold: 0.97
  c97:
    start_clickable_threshold: 0.97
  c99:
    start_clickable_threshold: 0.99
  c99s:
    distance_threshold: 1.99
    cluster_count_threshold: 6
    start_clickable_threshold: 0.99
  c95s:
    distance_threshold: 1.99
    cluster_count_threshold: 6
    start_clickable_threshold: 0.95

